### ISSUE TITLE
Suggestion: additional tags

### ISSUE THREAD

**Issue by ravenruis** [pcsg/steempunknet#20]
Currently, the @steempunksnet a/c only uses 2 tags:
![image](https://user-images.githubusercontent.com/38365152/40808870-b5030bc0-657c-11e8-83c9-32468c5ae7c7.png)

As we have space to use 5 tags, I suggest further ones are added in order to try and reach more people, especially as more and more are using services such as GINAbot to notify them of posts they are interested in, using the tag or keyword system.
My suggestions include:
gaming
mmorpg
steempunknet

Which would coordinate well with tags used on the main a/c, @steempunknet
![image](https://user-images.githubusercontent.com/38365152/40809072-56f29de2-657d-11e8-9a83-651b5a2db3f2.png)

:)

**Comment by dehenne** [comment]
is implemented
