### ISSUE TITLE
Request: Expose the fighterID field in the Fighters result set

### ISSUE THREAD

**Issue by TrisquelWhare** [pcsg/steempunknet#22]
I assume that the `attackerID` and `defenderID` fields (as used in the **Battles** result set), gets pulled from the **Fighters** table somehow, presumably. But the API doesn't currently seem to expose what I assume to be the "`fighterID`" field of the **Fighters** table. Could we please have the `fighterID` exposed, so that https://www.steempunk.net/api/spn/v1/fighters can generate a list of all registered fighters and their respective `fighterID`, which can then be used externally (such as in my LibreOffice Calc spreadsheet) to compare to the `attackerID` and `defenderID` fields of the **Battles** result set. I hope that all makes sense.

I'm attaching a screenshot of my LibreOffice Calc file, showing how I'm using this at the moment. I use the `=VLOOKUP()` function to compare the `attackerID` or `defenderID` fields of the **battles** sheet, to my manually collected  list of `fighterID`'s from the **fighters** sheet, to be able to pull the `username` in from **fighters**.

![180813_0552_spreadsheet-example](https://user-images.githubusercontent.com/39004110/44004848-3bda5fbc-9e59-11e8-82b1-bc19dab2013f.png)

**Comment by dehenne** [comment]
https://www.steempunk.net/api/spn/v1/fighters?details=1 :-)
