### ISSUE TITLE
Error when Change the Language in the Game Settings from German to English

### ISSUE THREAD

**Issue by louis88-steemit** [pcsg/steempunknet#3]
#### Expected behavior
With the game STEEMPUNKNET you have the possibility to change your language from German to English in the settings of the game. I expect the game to work wonderfully after that. Unfortunately, I get an error after saving the language.

#### Actual behavior
If you change the language in the game settings from German to English and save it, there is an error message. This error message cannot be prevented and if you want to continue playing the game, you have to reload the page completely. I have shown them once in a screenshot / animation for a better illustration. 

#### How to reproduce
Go to the game of STEEMPUNKNET - Log in there in the German language. When you are logged in, change to the game settings. In the game settings, simply change the language from German to English and save it.

You will get an error message.

* Browser: All Browser
* Operating system: All Operating System where you can play STEEMPUNK.

#### Recording Of The Bug
![enter image description here](https://i.imgur.com/tvmsbbv.png?1)

![enter image description here](https://media.giphy.com/media/8cNdVHE2GsSb4yUsjn/giphy.gif)
    
![screen](https://i.imgur.com/jSvy0RC.png)
<sub> [Link to Large Image](https://i.imgur.com/jSvy0RC.png) - Error Message for the Bug </sub>

----------

Thanks - @louis88

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/error-when-change-the-language-in-the-game-settings-from-german-to-english">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dehenne** [comment]
Ok is fixed ;-) Thank you for reporting
