### ISSUE TITLE
Button clickable without the requirements + Empty error message in Housing feature

### ISSUE THREAD

**Issue by k3lda** [pcsg/steempunknet#6]
#### Expected behavior
In Steempunk you now have the possibility to build your own house within the housing feature. Therefore you need a lot of materials, for example wood. If you do not have enough ressources to build something, the "Upgrade"-Button should be red or not clickable or even if you click on "Upgrade" while not having the correct amount of ressources, an error message should show up.

#### Actual behavior
After opening the special index tab of the housing feature you can see, that you do not have enough materials (the needed amount of wood is displayed in red). But the "Upgade"-Button is displayed in green and clickable. If you click on the "Upgrade-Button, an empty notification message will pop up.

#### How to reproduce 
Open the game Steempunk while beeing on Steemit. After logging in, go to the index tab of housing (the fourth tab in the bar). Then you have to click on "House settings" and again on the first "Upgrade-Button". Now the empty error message  shows up. If click an additional time on "House settings" the "Upgrade"-Button is green again and you can reproduce the bug as often you want.

Operating system: Every operating system u can use to play Steempunk<p>
Browser: All Browsers

#### Recording of the bug
![not enough wood.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521118072/jls5t9lkjsfzxb41gnv6.png)

![Housing Button aviable, aber zu wenig Rohstoffe.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521117546/p9b4vzcqtrvvct8csubo.jpg)
Not enough ressources (here: wood), but "Upgrade"-Button is clickable

![leere Fehlermeldung.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521117725/intf5fnmjcaehu7fmqvl.jpg)
Empty notification message (nothing else happens

![housing leere fehlermeldung gif.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521117767/sagio1pvqdhlxllsd6wd.gif)
How to reproduce the bug

Hopefully you can fix this irritating bug.

Greets k3lda

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@k3lda/button-clickable-without-the-requirements-empty-error-message-in-housing-feature">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dehenne** [comment]
With the next update it should fixed.
https://github.com/pcsg/steemit-steempunk-battle/commit/4c79901c8d8bf1013f5d238304aa36bd9c901bcc
