### ISSUE TITLE
No notification message when invetory is full + No way to get rid of items

### ISSUE THREAD

**Issue by k3lda** [pcsg/steempunknet#8]
#### Expected behavior
In Steempunk I reached the maximum of materials, which is exactly 1001 items. When trying to open new lootboxes, an error message like "Your Inventory is already full" or "You can not get more items" is expected. Otherwise you should be able to remove some unneeded items, to throw them away or maybe trade them with other players of Steempunk to get more space for other needed components.

#### Actual behavior
When your inventory is at its maximum of storage and you still try to collect Items really nothing happens except the disappearance of the boxes; Neither notification messages or items will appear.
For housing feature you need a definite number of a certain material to build something. When your inventory is at its limit and you are not able to dump some other materials, you will never be able to do anything in housing. Opening boxes also looses attractivity., because there is no further use for it.

#### How to reproduce
Play Steempunk and keep opening lootboxes until you reached the maximal amount of items. Then try to open even more boxes. As already described, nothing except the disappearance of the boxes will be the result. Nothing else changes. Dropping the items is also not possible yet.  

* Browser: All Browsers
* Operating system: Every operating system u can use to play Steempunk

#### Recording Of The Bug
![full items 1001.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521338811/yhwbhjysolmotrojeat3.jpg)
Full inventory with 1001 items 

![Housing Button aviable, aber zu wenig Rohstoffe.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521339232/havtnlhplqjdepuffqbo.jpg)
Needed amount of specific material to use housing feature

![keine fehlermeldung wenn items voll.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521339001/adnqprpvsnnfr3po2vbf.gif)
How to reproduce with a full inventory

Hopefully you can fix this, so housing can be used properly and boxes keep their value!

Greets k3lda

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@k3lda/no-notification-message-when-invetory-is-full-no-way-to-get-rid-of-items">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dehenne** [comment]
Done with the next update:
https://steemit.com/utopian-io/@pcsg-dev/steempunk-net-item-dropping-and-delegating-are-coming
